FROM ubuntu/mysql:8.0-20.04_beta

RUN set -eux; \
    apt-get update; \
    apt-get install -y \
        bash \
        bash-completion \
        curl \
        openssl \
        git \
        make \
        grep \
        jq \
        unzip \
        wget \
        nano \
        zlib1g-dev \
        libzip-dev \
        iputils-ping \
        procps \
        pv \
    ; \
